quine-sh/Your-First-Contribution

- QuineContributors.md
Added my name in contributors.md
> Updated contributors.md

- QuineContributors.md
- Last person didn't closed the tag properly coz we need 8 people on one row but it was getting 4 persons per page, so I changed the "tr" tag and made it "td" -added my name in QuineContributors
> Changed some line of code and als0 added my name in it

- QuineContributors.md
One small contribution to Quine. Good idea!
> Oleg Rybnikov

- QuineContributors.md
montsea999 opensource contribution.
> Montserrat Álvarez

- QuineContributors.md
> Anurag Singh

- QuineContributors.md
> Nikola Badjevic

- QuineContributors.md
It was great to learn how Github Contribution works!
> First Github Contribution

- QuineContributors.md
Hi, I have added my name to the QuineContributors.md file in the repository. Please accept.
> Added my name to QuineContributors.md

- QuineContributors.md
Added my own name Shibam Roy to the contributers list file ( "QuineContributors.md")
> Added My name to the contributers list

- QuineContributors.md
> Nikhil Gautam | added my name and username

- QuineContributors.md
Adjusted indention and added contributor entry
> Jason Zamora aka GS

- QuineContributors.md
Added me in the list thank you :)
> Add new contributor

- QuineContributors.md
Making Contribution in Open Source. 
Thanks for considering it.
> Contributing to Open Source

- QuineContributors.md
> feat: 📝add contributors

- QuineContributors.md
> Added Name

- QuineContributors.md
> Muhammad Mehdy

- QuineContributors.md
Just Got successfully contributed first time to quine.
> TYMNS PAYCE

- QuineContributors.md
Hey!
I just added my username and and github profile link! I hope this pull request is merged!
Thanks to Fernandez for the yt tutorial!
A fellow contributor,
Peme969
> Added my name 😁

- QuineContributors.md
> Jainil Jain 

- QuineContributors.md
Hello team,
I've made a contribution by adding my name to the list of contributors. Please review the changes to ensure everything is in order. I'm excited to be part of this project and look forward to contributing more in the future.
Thank you!
ART-Coby
> Add contribution from ART-Coby to the list of contributors

- QuineContributors.md
Hi, just added my name Marina Kim | marinakim44 to the list of Quine Contributors :)
> add Marina Kim marinakim44 to the contributors

- QuineContributors.md
Its my first contribution and i added my name with my github link.....
> Its my first contribution and i added my name with my github link

- QuineContributors.md
added name to list of contributors
> added name to list of contributors

- QuineContributors.md
> Sohan Venkatesh
